<h2><a href="{plink Quiz:}">Quiz:</a></h2>

{if isset($new_form)}
	<div class="block">
	{$new_form}
	</div>
{/if}

@{if isset($quiz)}
{snippet quiz}

		{if $quiz['run'] == 0}
			<div id="quiz-countdown">
				Quiz start <strong>{$quiz['datetime_start']|date:'%H:%M:%S - %d.%m.%Y'}</strong>
			</div>
		{/if}

		@{if isset($question)}
	
			@{$question->render()}
	
		@{/if}
	
		@{if isset($chart)}
	
			@{$chart->render()}
	
		@{/if}

{/snippet}

<script type="text/javascript">
//<![CDATA[

	var quiz_config = {
		"form" : "qform",
		"url" : {plink Quiz:},
		"hint_url" : {plink Quiz:hint},
		"answer_url" : {plink Quiz:answer},
	{if isset($question)}
		"question" : {
			"id" 	: {$question->id},
			"time" 	: {$question->time},
			"hints"	: {$question->hints},
			"type" 	: {$question->type}
		},
	{/if}
		"time" : {$quiz['time']}
	 };
//]]>
</script>

@{/if}
