{snippet paginator}

<div class="paginator">
	{if $paginator->isFirst()}
	<span class="button">« Previous</span>
	{else}
	<a href="{link page $paginator->page - 1}" {if $useAjax}onclick="return !nette.action(this)"{/if}>« Previous</a>
	{/if}

	{foreach $steps as $step}
	{if isset($prevStep) && $step - $prevStep > 1}<span>…</span>{/if}
	{if $step == $paginator->page}
		<span class="current">{$step}</span>
	{else}
		<a href="{link page $step}" {if $useAjax}onclick="return !nette.action(this)"{/if}>{$step}</a>
	{/if}
	{? $prevStep = $step }
	{/foreach}

	{if $paginator->isLast()}
	<span class="button">Next »</span>
	{else}
	<a href="{link page, $paginator->page + 1}" {if $useAjax}onclick="return !nette.action(this)"{/if}>Next »</a>
	{/if}

	
</div>
{if $filter_options}
{/* todo */}
<div class="filter">
	{foreach $filter_options as $option}
		
	{/foreach}
</div>
{/if}
{/snippet}